#!/bin/bash

function pubfile()
{
	if [ ! -f $1 ]; then
		echo ERROR: File $1 does not exist.
		exit
	fi

	dstfile=~/bin/$2
	echo Publishing $1...
	cp $1 $dstfile
	chmod +x $dstfile
	if [ $3 = true ]; then
		echo Optimizing $dstfile...
		mono --aot -O=all $dstfile
	fi
}

if [ -z "$1" ]; then
	buildconfig=Release
else
	buildconfig=Debug
fi

# Publish CDD files
subfolder=cddx/bin/$buildconfig
pubfile $subfolder/cddx.exe cddx.exe true
pubfile cddx/cdd.sh cdd.sh false

# Publish PDD files
subfolder=pddx/bin/$buildconfig
pubfile $subfolder/pddx.exe pddx.exe true
pubfile pddx/pdd.sh pdd.sh false

# Publish SDD files
subfolder=sdd/bin/$buildconfig
pubfile $subfolder/sdd.exe sddx.exe true
pubfile sdd/sdd.sh sdd.sh false

echo
echo Add the following aliases to your .bashrc file:

cat cddx/aliases
